version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"  # Expondo a porta 80 no contêiner para a 3000 localmente
    
    networks:
      - app_net


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "3001:3000"  # Expondo a porta 3000 do backend para a 3001 localmente
    environment:
      DB_HOST: db  # Nome do serviço do banco de dados
      DB_USER: root
      DB_PASSWORD: 09229009
      DB_NAME: biblioteca_virtual
      DB_PORT: 3306
    depends_on:
      - db
      
    networks:
      - app_net


  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3306:3306"  # Expondo a porta padrão do MySQL
    environment:
      MYSQL_ROOT_PASSWORD: 09229009  # Segurança básica com senha para root
      MYSQL_DATABASE: biblioteca_virtual
    volumes:
      - db_data:/var/lib/mysql  # Persistência dos dados do banco
    networks:
      - app_net

networks:
  app_net:
    driver: bridge  # Rede para comunicação entre os contêineres

volumes:
  db_data:  # Volume para dados persistentes do MySQL
