version: "3.8"

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"  # Expondo a porta 80 no contêiner para a 3000 localmente
    
    networks:
      - app_net


  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend_container
    ports:
      - "4000:3000"  # Expondo a porta 3000 do backend para a 4000 localmente
    environment:
      DB_HOST: db
      DB_USER: root
      DB_PASSWORD: 09229009
      DB_NAME: biblioteca_virtual
      DB_PORT: 3307
    depends_on:
      - db
      
    networks:
      - app_net


  db:
    image: mysql:latest
    container_name: mysql_container
    ports:
      - "3307:3307"
    environment:
      MYSQL_ROOT_PASSWORD: 09229009  #senha para root
      MYSQL_DATABASE: biblioteca_virtual
    volumes:
      - db_data:/var/lib/mysql  # Persistência dos dados do banco
    networks:
      - app_net

networks:
  app_net:
    driver: bridge  # Rede para comunicação entre os contêineres

volumes:
  db_data:  # Volume para dados persistentes do MySQL
