version: "3.8"
#Rever, possivel erro
services:
  frontend:
    build:
      context: ./frontend         # Diretório frontend 
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "3000:80"
    depends_on:
      - backend
    networks:
      - app_net

  backend:
    build:
      context: ./backend          # Diretório backend
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/usr/src/app
    depends_on:
      - db
    networks:
      - app_net

  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: sua-senha
      MYSQL_DATABASE: biblioteca
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - app_net

volumes:
  db_data:

networks:
  app_net:
    driver: bridge
