version: "3.8" #Tudo aqui é exemplo

services:
  frontend: 
    image: node:8 #Apache (Adaptar)
    container_name: node_app
    ports:
      - "3000:3000"
    command: 
      ["npm", "start"]  # Define o comando de inicialização
    networks:
      - app_net  # Conecta o container à rede personalizada
    volumes: #jaja eu mexo, to aprendendo
      - ./app:/usr/src/app

  backend:
    image: node:8 #Node.js (Adaptar)
    container_name: node_app
    ports:
      - "3000:3000"
    command: 
      ["npm", "start"]
    networks:
      - app_net
    volumes:
      - ./app:/usr/src/app

  db: #obrigatoriamente mysql
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge