version: "3.8" #Falta testar
#Bglh cheio de n me toque, um espaço da problema em tudo, um enter da problema em tudo

services:
  frontend: 
    image: nginx:latest          #Mais facil
    container_name: frontend
    ports:                       #http://localhost:8080
      - "3000:80"                
    volumes:                     #front --> diretorio nginx
      - ../frontend:/usr/share/nginx/html 
    depends_on:
      - backend                   # back ativo antes do front
    networks:
      - app_net                   # rede app_net

    
  backend:
    build:
      context: ../backend          # Diretório dockerfile backend
      dockerfile: Dockerfile       # construi a imagem
    container_name: backend
    ports:
      - "3001:3001"                #localhost:3001
    volumes:
      - ../backend:/usr/src/app    # Mapeia os arquivos do backend
    depends_on:
      - db                         # bd ativo antes do backend
    networks:
      - app_net


  db:
    image: mysql:latest
    container_name: db
    ports:
      - "3306:3306"                # porta padrão do MySQL, só n mexe, dá muito problema
    environment:
      MYSQL_ROOT_PASSWORD: sua-senha
      MYSQL_DATABASE: biblioteca   # faz o banco "biblioteca"
    volumes:
      - db_data:/var/lib/mysql     # mantem os dados do banco
    networks:
      - app_net

volumes:
  db_data:                         # volume para manter os dados do banco

networks:
  app_net:                         # rede para conectar os serviços
    driver: bridge
