version: "3.8" #Tudo aqui é exemplo

services:
  app: # Escolhe ai #Vai precisar de 3 desse, no min
    image: node:8 #Cada serviço deve estar em 1 containêr
    container_name: node_app
    ports: #requisição de portas
      - "3000:3000"
    command: 
      ["npm", "start"]  # Define o comando de inicialização
    networks:
      - app_net  # Conecta o container à rede personalizada
    volumes: #jaja eu mexo, to aprendendo
      - ./app:/usr/src/app

  db:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: myappdb
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


volumes:
  mysql_data:

networks:
  app_net:
    driver: bridge